;;; fanyi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fanyi.el

(autoload 'fanyi-dwim "fanyi" "\
Translate WORD.

(fn WORD)" t)
(autoload 'fanyi-dwim2 "fanyi" "\
A more dwim version of `fanyi-dwim'.
No prompt if the region is active or `thing-at-point' returns
non-nil." t)
(autoload 'fanyi-from-history "fanyi" "\
Invoke `fanyi-dwim' from history." t)
(autoload 'fanyi-bookmark-jump "fanyi" "\
Default BOOKMARK handler for fanyi.

(fn BOOKMARK)")
(register-definition-prefixes "fanyi" '("fanyi-"))


;;; Generated autoloads from fanyi-base.el

(register-definition-prefixes "fanyi-base" '("fanyi-"))


;;; Generated autoloads from fanyi-etymon.el

(register-definition-prefixes "fanyi-etymon" '("fanyi-etymon-"))


;;; Generated autoloads from fanyi-haici.el

(register-definition-prefixes "fanyi-haici" '("fanyi-haici-"))


;;; Generated autoloads from fanyi-longman.el

(register-definition-prefixes "fanyi-longman" '("fanyi-longman-"))


;;; Generated autoloads from fanyi-youdao-thesaurus.el

(register-definition-prefixes "fanyi-youdao-thesaurus" '("fanyi-youdao-thesaurus-"))


;;; Generated autoloads from ol-fanyi.el

(register-definition-prefixes "ol-fanyi" '("fanyi-org-"))

;;; End of scraped data

(provide 'fanyi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fanyi-autoloads.el ends here
